services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./api:/app  # Monte le répertoire local ./api dans le conteneur
      - /app/node_modules  # Préserve node_modules du conteneur
    ports:
      - "3000:3000"
    env_file:
      - .env
    
    environment:
      - NODE_ENV=development
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - PORT=3000
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongodb

  mongodb:
    build:
      context: .
      dockerfile: docker/mongoDB/Dockerfile
    ports:
      - "27017:27017"
