version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=f1_reaction_timer
    depends_on:
      - mongodb

  mongodb:
    build:
      context: .
      dockerfile: docker/mongoDB/Dockerfile
    ports:
      - "27017:27017"